import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "~/app/api/uploadthing/core";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import TopNav from "./_components/TopNav";
import { extractRouterConfig } from "uploadthing/server";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Planet Cure",
  description: "Generated by Graphathons",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} dark`}>
        <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <div className="h-screen grid grid-rows-[auto,1fr]">
          <TopNav/>
          <main className=" overflow-y-auto">
            {children}
          </main>
        </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
