import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import TopNav from "./_components/TopNav";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Planet Cure",
  description: "Generated by Graphathons",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} dark`}>
        <div className="h-screen grid grid-rows-[auto,1fr]">
          <TopNav/>
          <main className=" overflow-y-auto">
            {children}
          </main>
        </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
